(define (problem corridor_6)
  (:domain corridor)
  (:objects l1 l2 l3 l4 l5 l6 l7 l8 - object )
  (:init (at l2)
    (goal_at l8)
    (adjacent l1 l2)    
(adjacent l2 l3)    
(adjacent l3 l4)    
(adjacent l4 l5)    
(adjacent l5 l6)    
(adjacent l6 l7)    
(adjacent l7 l8))
  (:goal (and (at l8))))
