
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear m)
        (clear c)
        (clear f)
        (clear g)
        (clear l)
        (clear k)
        (ontable c)
        (ontable j)
        (ontable e)
        (ontable f)
        (ontable g)
        (ontable n)
        (on k h)
        (on d i)
        (on m j)
        (on a d)
        (on l b)
        (on b e)
        (on i n)
        (on h a)
        (handempty )
    )

    (:goal
        (and (clear m) (clear c) (clear f) (clear l) (clear k) (ontable c) (ontable j) (ontable e) (ontable f) (ontable n) (on k h) (on d i) (on m j) (on a d) (on l b) (on b e) (on i n) (on h a) (holding g))
    )

    
    
    
)

