
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear b)
        (clear c)
        (clear j)
        (clear e)
        (clear g)
        (clear k)
        (ontable b)
        (ontable c)
        (ontable h)
        (ontable f)
        (ontable k)
        (ontable n)
        (on j i)
        (on d m)
        (on e l)
        (on m a)
        (on g d)
        (on l f)
        (on i n)
        (on a h)
        (handempty )
    )

    (:goal
        (and (clear c) (clear j) (clear e) (clear g) (clear k) (ontable h) (ontable c) (ontable f) (ontable k) (ontable n) (on d m) (on e l) (on i n) (on m a) (on l f) (on g d) (on j i) (on a h) (holding b))
    )

    
    
    
)

