
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear l)
        (clear e)
        (ontable e)
        (ontable h)
        (on n c)
        (on f b)
        (on l f)
        (on d m)
        (on b j)
        (on i n)
        (on k g)
        (on m a)
        (on c k)
        (on a h)
        (on g d)
        (on j i)
        (handempty )
    )

    (:goal
        (and (clear l) (ontable h) (on n c) (on f b) (on j i) (on d m) (on b j) (on k g) (on m a) (on g d) (on c k) (on l f) (on i n) (on a h) (holding e))
    )

    
    
    
)

