
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-10-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j - object
    )

    (:init
        (clear d)
        (clear b)
        (clear a)
        (clear h)
        (clear j)
        (ontable b)
        (ontable h)
        (ontable i)
        (ontable e)
        (ontable f)
        (on j e)
        (on a g)
        (on d c)
        (on g i)
        (on c f)
        (handempty )
    )

    (:goal
        (and (clear d) (clear a) (clear h) (clear j) (ontable h) (ontable i) (ontable e) (ontable f) (on a g) (on j e) (on d c) (on g i) (on c f) (holding b))
    )

    
    
    
)

