
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-10-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j - object
    )

    (:init
        (clear d)
        (clear b)
        (clear h)
        (clear j)
        (ontable i)
        (ontable e)
        (ontable f)
        (ontable h)
        (on j e)
        (on a g)
        (on b a)
        (on d c)
        (on g i)
        (on c f)
        (handempty )
    )

    (:goal
        (and (clear j) (clear d) (clear b) (ontable i) (ontable e) (ontable f) (on a g) (on j e) (on b a) (on d c) (on g i) (on c f) (holding h))
    )

    
    
    
)

