
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-11-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k - object
    )

    (:init
        (clear b)
        (clear a)
        (clear h)
        (clear e)
        (clear f)
        (clear k)
        (ontable d)
        (ontable b)
        (ontable h)
        (ontable c)
        (ontable i)
        (ontable k)
        (on e g)
        (on f i)
        (on g c)
        (on a j)
        (on j d)
        (handempty )
    )

    (:goal
        (and (clear a) (clear h) (clear e) (clear f) (clear k) (ontable d) (ontable c) (ontable h) (ontable i) (ontable k) (on e g) (on f i) (on g c) (on a j) (on j d) (holding b))
    )

    
    
    
)

