
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-11-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k - object
    )

    (:init
        (clear j)
        (clear d)
        (clear b)
        (clear a)
        (ontable j)
        (ontable d)
        (ontable a)
        (ontable c)
        (on i f)
        (on e g)
        (on k i)
        (on b h)
        (on f e)
        (on g c)
        (on h k)
        (handempty )
    )

    (:goal
        (and (clear j) (clear d) (clear b) (ontable j) (ontable d) (ontable c) (on i f) (on e g) (on k i) (on b h) (on f e) (on g c) (on h k) (holding a))
    )

    
    
    
)

