
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear d)
        (clear b)
        (clear a)
        (clear j)
        (clear e)
        (clear g)
        (ontable h)
        (ontable j)
        (ontable c)
        (ontable f)
        (ontable g)
        (ontable k)
        (on i c)
        (on d i)
        (on e k)
        (on l f)
        (on a h)
        (on b l)
        (handempty )
    )

    (:goal
        (and (clear d) (clear b) (clear a) (clear e) (clear g) (ontable c) (ontable h) (ontable f) (ontable g) (ontable k) (on i c) (on l f) (on e k) (on d i) (on a h) (on b l) (holding j))
    )

    
    
    
)

