
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear i)
        (clear c)
        (ontable i)
        (ontable g)
        (on j e)
        (on f a)
        (on k f)
        (on d j)
        (on e k)
        (on h g)
        (on l d)
        (on a h)
        (on b l)
        (on c b)
        (handempty )
    )

    (:goal
        (and (clear c) (ontable g) (on j e) (on f a) (on k f) (on d j) (on e k) (on h g) (on l d) (on a h) (on b l) (on c b) (holding i))
    )

    
    
    
)

