
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-10-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j - object
    )

    (:init
        (clear b)
        (clear a)
        (clear c)
        (clear h)
        (clear e)
        (clear g)
        (ontable h)
        (ontable j)
        (ontable i)
        (ontable e)
        (ontable f)
        (ontable g)
        (on b f)
        (on c j)
        (on a d)
        (on d i)
        (handempty )
    )

    (:goal
        (and (clear b) (clear a) (clear h) (clear c) (clear g) (ontable h) (ontable j) (ontable i) (ontable f) (ontable g) (on b f) (on d i) (on a d) (on c j) (holding e))
    )

    
    
    
)

