
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-13-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m - object
    )

    (:init
        (clear a)
        (clear j)
        (clear g)
        (clear l)
        (ontable l)
        (ontable e)
        (ontable f)
        (ontable k)
        (on i c)
        (on b k)
        (on h e)
        (on m h)
        (on j b)
        (on d f)
        (on a m)
        (on g i)
        (on c d)
        (handempty )
    )

    (:goal
        (and (clear j) (clear g) (clear a) (ontable e) (ontable f) (ontable k) (on i c) (on b k) (on h e) (on c d) (on m h) (on d f) (on a m) (on g i) (on j b) (holding l))
    )

    
    
    
)

