
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem briefcase-o14)
    (:domain briefcase)

    (:objects
        l0 l1 l10 l11 l12 l13 l14 l2 l3 l4 l5 l6 l7 l8 l9 - location
        o0 o1 o10 o11 o12 o13 o2 o3 o4 o5 o6 o7 o8 o9 - portable
    )

    (:init
        (at o0 l5)
        (at o8 l7)
        (at o12 l12)
        (at o3 l12)
        (at o9 l12)
        (at o1 l5)
        (at o13 l11)
        (at o4 l5)
        (at o11 l6)
        (at o7 l5)
        (at o2 l5)
        (at o5 l5)
        (at o6 l13)
        (at o10 l11)
        (is-at l5)
        (in o0)
        (in o2)
        (in o7)
        (in o1)
        (in o5)
        (in o4)
    )

    (:goal
        (and (at o12 l12) (at o7 l2) (at o11 l6) (at o6 l13) (at o4 l2) (at o8 l7) (at o3 l12) (at o9 l12) (at o13 l11) (at o5 l2) (at o2 l2) (at o0 l2) (at o1 l2) (at o10 l11) (is-at l2) (in o0) (in o2) (in o1) (in o7) (in o5) (in o4))
    )

    
    
    
)

