
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem briefcase-o15)
    (:domain briefcase)

    (:objects
        l0 l1 l10 l11 l12 l13 l14 l15 l2 l3 l4 l5 l6 l7 l8 l9 - location
        o0 o1 o10 o11 o12 o13 o14 o2 o3 o4 o5 o6 o7 o8 o9 - portable
    )

    (:init
        (at o4 l8)
        (at o9 l4)
        (at o3 l14)
        (at o0 l12)
        (at o8 l5)
        (at o14 l1)
        (at o6 l0)
        (at o2 l4)
        (at o5 l4)
        (at o11 l4)
        (at o10 l10)
        (at o13 l6)
        (at o7 l1)
        (at o1 l6)
        (at o12 l0)
        (is-at l4)
        (in o2)
        (in o11)
    )

    (:goal
        (and (at o4 l8) (at o9 l4) (at o3 l14) (at o0 l12) (at o8 l5) (at o14 l1) (at o2 l10) (at o6 l0) (at o11 l10) (at o5 l4) (at o10 l10) (at o13 l6) (at o7 l1) (at o1 l6) (at o12 l0) (is-at l10) (in o2) (in o11))
    )

    
    
    
)

