
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem briefcase-o11)
    (:domain briefcase)

    (:objects
        l0 l1 l10 l11 l2 l3 l4 l5 l6 l7 l8 l9 - location
        o0 o1 o10 o2 o3 o4 o5 o6 o7 o8 o9 - portable
    )

    (:init
        (at o2 l11)
        (at o8 l10)
        (at o4 l10)
        (at o6 l2)
        (at o7 l4)
        (at o0 l11)
        (at o3 l11)
        (at o1 l1)
        (at o10 l4)
        (at o5 l11)
        (at o9 l6)
        (is-at l11)
        (in o0)
        (in o2)
        (in o5)
    )

    (:goal
        (and (at o0 l0) (at o8 l10) (at o4 l10) (at o6 l2) (at o7 l4) (at o3 l11) (at o5 l0) (at o1 l1) (at o10 l4) (at o2 l0) (at o9 l6) (is-at l0) (in o0) (in o2) (in o5))
    )

    
    
    
)

