
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear g)
        (clear a)
        (ontable e)
        (ontable n)
        (on h m)
        (on k c)
        (on m k)
        (on d i)
        (on c l)
        (on g d)
        (on a j)
        (on l b)
        (on b e)
        (on j h)
        (on i n)
        (holding f)
    )

    (:goal
        (and (clear g) (clear f) (clear a) (ontable e) (ontable f) (ontable n) (on h m) (on k c) (on m k) (on i n) (on d i) (on c l) (on a j) (on l b) (on b e) (on j h) (on g d) (handempty ))
    )

    
    
    
)

