
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear m)
        (clear a)
        (clear h)
        (clear j)
        (clear c)
        (ontable c)
        (ontable h)
        (ontable e)
        (ontable k)
        (ontable n)
        (on d i)
        (on a d)
        (on j k)
        (on b e)
        (on l b)
        (on m f)
        (on i n)
        (on f l)
        (holding g)
    )

    (:goal
        (and (clear m) (clear a) (clear c) (clear j) (clear h) (clear g) (ontable h) (ontable c) (ontable e) (ontable g) (ontable k) (ontable n) (on d i) (on a d) (on j k) (on l b) (on b e) (on m f) (on i n) (on f l) (handempty ))
    )

    
    
    
)

