
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear m)
        (clear b)
        (clear e)
        (clear k)
        (ontable j)
        (ontable f)
        (ontable n)
        (ontable h)
        (on e l)
        (on b j)
        (on k g)
        (on d i)
        (on m a)
        (on g d)
        (on l f)
        (on i n)
        (on a h)
        (holding c)
    )

    (:goal
        (and (clear m) (clear b) (clear c) (clear e) (clear k) (ontable c) (ontable j) (ontable h) (ontable f) (ontable n) (on e l) (on b j) (on i n) (on k g) (on m a) (on d i) (on l f) (on g d) (on a h) (handempty ))
    )

    
    
    
)

