
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear m)
        (clear b)
        (clear d)
        (clear c)
        (clear j)
        (clear e)
        (clear k)
        (ontable b)
        (ontable h)
        (ontable j)
        (ontable c)
        (ontable f)
        (ontable k)
        (ontable n)
        (on e l)
        (on m a)
        (on d i)
        (on l f)
        (on i n)
        (on a h)
        (holding g)
    )

    (:goal
        (and (clear d) (clear m) (clear b) (clear c) (clear j) (clear e) (clear g) (clear k) (ontable b) (ontable c) (ontable j) (ontable h) (ontable f) (ontable g) (ontable k) (ontable n) (on e l) (on d i) (on m a) (on l f) (on i n) (on a h) (handempty ))
    )

    
    
    
)

