
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-11-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k - object
    )

    (:init
        (clear j)
        (clear e)
        (clear b)
        (ontable d)
        (ontable i)
        (ontable e)
        (on k a)
        (on f i)
        (on b g)
        (on g h)
        (on j d)
        (on h k)
        (on a f)
        (holding c)
    )

    (:goal
        (and (clear j) (clear e) (clear b) (clear c) (ontable e) (ontable i) (ontable d) (ontable c) (on k a) (on f i) (on g h) (on b g) (on j d) (on h k) (on a f) (handempty ))
    )

    
    
    
)

