
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear g)
        (clear a)
        (clear h)
        (ontable l)
        (ontable a)
        (ontable c)
        (on i c)
        (on k e)
        (on j l)
        (on h j)
        (on b d)
        (on d i)
        (on g k)
        (on e b)
        (holding f)
    )

    (:goal
        (and (clear g) (clear f) (clear a) (clear h) (ontable l) (ontable f) (ontable a) (ontable c) (on i c) (on h j) (on k e) (on j l) (on b d) (on d i) (on g k) (on e b) (handempty ))
    )

    
    
    
)

