
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear a)
        (clear j)
        (clear e)
        (clear g)
        (clear l)
        (ontable c)
        (ontable j)
        (ontable h)
        (ontable f)
        (ontable g)
        (on i c)
        (on b d)
        (on d i)
        (on e b)
        (on l f)
        (on a h)
        (holding k)
    )

    (:goal
        (and (clear a) (clear j) (clear e) (clear g) (clear l) (clear k) (ontable h) (ontable j) (ontable c) (ontable f) (ontable g) (ontable k) (on i c) (on b d) (on d i) (on e b) (on l f) (on a h) (handempty ))
    )

    
    
    
)

