
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear i)
        (clear e)
        (clear l)
        (clear k)
        (ontable d)
        (ontable g)
        (ontable e)
        (ontable b)
        (on i c)
        (on f a)
        (on k f)
        (on h g)
        (on l d)
        (on a h)
        (on c b)
        (holding j)
    )

    (:goal
        (and (clear j) (clear i) (clear e) (clear l) (clear k) (ontable d) (ontable b) (ontable j) (ontable e) (ontable g) (on i c) (on f a) (on k f) (on h g) (on l d) (on a h) (on c b) (handempty ))
    )

    
    
    
)

