
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem strips-gripper-x-3)
    (:domain gripper-strips)

    (:objects
        ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 left right rooma roomb - object
    )

    (:init
        (room rooma)
        (room roomb)
        (ball ball8)
        (ball ball3)
        (ball ball4)
        (ball ball5)
        (ball ball1)
        (ball ball2)
        (ball ball7)
        (ball ball6)
        (at-robby roomb)
        (at ball6 rooma)
        (at ball8 rooma)
        (at ball7 rooma)
        (at ball3 roomb)
        (at ball5 roomb)
        (at ball2 roomb)
        (gripper left)
        (gripper right)
        (carry ball1 right)
        (carry ball4 left)
    )

    (:goal
        (and (room rooma) (room roomb) (ball ball8) (ball ball3) (ball ball6) (ball ball5) (ball ball1) (ball ball2) (ball ball7) (ball ball4) (at-robby rooma) (at ball6 rooma) (at ball2 roomb) (at ball7 rooma) (at ball3 roomb) (at ball5 roomb) (at ball8 rooma) (gripper left) (gripper right) (carry ball1 right) (carry ball4 left))
    )

    
    
    
)

