
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-4-0)
    (:domain BLOCKS)

    (:objects
        a b c d - object
    )

    (:init
        (clear a)
        (clear d)
        (clear c)
        (ontable a)
        (ontable d)
        (ontable c)
        (holding b)
    )

    (:goal
        (and (clear d) (clear b) (clear c) (ontable a) (ontable d) (ontable c) (handempty ) (on b a))
    )

    
    
    
)

