
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear c)
        (ontable a)
        (on b a)
        (on e b)
        (on c e)
        (holding d)
    )

    (:goal
        (and (clear d) (ontable a) (on b a) (on d c) (on e b) (on c e) (handempty ))
    )

    
    
    
)

