
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear d)
        (clear e)
        (ontable a)
        (ontable b)
        (on e a)
        (on d b)
        (holding c)
    )

    (:goal
        (and (clear d) (clear c) (ontable a) (ontable b) (on e a) (on d b) (on c e) (handempty ))
    )

    
    
    
)

