
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear a)
        (clear d)
        (clear c)
        (ontable a)
        (ontable b)
        (ontable f)
        (on c b)
        (on d f)
        (holding e)
    )

    (:goal
        (and (clear a) (clear e) (clear c) (ontable a) (ontable b) (ontable f) (on c b) (on e d) (on d f) (handempty ))
    )

    
    
    
)

