
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-7-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g - object
    )

    (:init
        (clear a)
        (clear b)
        (clear c)
        (clear e)
        (ontable d)
        (ontable g)
        (ontable e)
        (ontable b)
        (on a g)
        (on c d)
        (holding f)
    )

    (:goal
        (and (clear a) (clear b) (clear c) (clear f) (ontable d) (ontable g) (ontable e) (ontable b) (on a g) (on f e) (on c d) (handempty ))
    )

    
    
    
)

