
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear a)
        (clear b)
        (clear c)
        (clear g)
        (clear h)
        (clear f)
        (ontable a)
        (ontable b)
        (ontable c)
        (ontable h)
        (ontable e)
        (ontable f)
        (on g e)
        (holding d)
    )

    (:goal
        (and (clear b) (clear c) (clear g) (clear d) (clear h) (clear f) (ontable a) (ontable b) (ontable c) (ontable h) (ontable e) (ontable f) (on g e) (on d a) (handempty ))
    )

    
    
    
)

