
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear b)
        (clear c)
        (clear d)
        (clear g)
        (clear e)
        (clear f)
        (ontable a)
        (ontable b)
        (ontable c)
        (ontable g)
        (ontable e)
        (ontable f)
        (on d a)
        (holding h)
    )

    (:goal
        (and (clear b) (clear c) (clear g) (clear h) (clear e) (clear f) (ontable a) (ontable b) (ontable c) (ontable g) (ontable e) (ontable f) (on h d) (on d a) (handempty ))
    )

    
    
    
)

