
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear b)
        (clear c)
        (clear d)
        (clear f)
        (ontable d)
        (ontable e)
        (ontable b)
        (ontable f)
        (on a g)
        (on g e)
        (on c a)
        (holding h)
    )

    (:goal
        (and (clear b) (clear d) (clear h) (clear f) (ontable d) (ontable e) (ontable b) (ontable f) (on a g) (on g e) (on c a) (on h c) (handempty ))
    )

    
    
    
)

