
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear a)
        (clear d)
        (clear h)
        (clear e)
        (ontable b)
        (ontable h)
        (ontable e)
        (ontable f)
        (on a g)
        (on g b)
        (on d f)
        (holding c)
    )

    (:goal
        (and (clear c) (clear d) (clear h) (clear e) (ontable e) (ontable b) (ontable f) (ontable h) (on a g) (on g b) (on c a) (on d f) (handempty ))
    )

    
    
    
)

