
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear d)
        (clear h)
        (ontable b)
        (ontable f)
        (on a g)
        (on h c)
        (on c a)
        (on g b)
        (on d f)
        (holding e)
    )

    (:goal
        (and (clear d) (clear e) (ontable b) (ontable f) (on a g) (on h c) (on e h) (on c a) (on g b) (on d f) (handempty ))
    )

    
    
    
)

