
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-13-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m - object
    )

    (:init
        (clear a)
        (clear h)
        (clear j)
        (clear e)
        (clear g)
        (ontable m)
        (ontable b)
        (ontable e)
        (ontable f)
        (ontable k)
        (on i c)
        (on l k)
        (on j b)
        (on d f)
        (on a m)
        (on h l)
        (on g i)
        (on c d)
        (handempty )
    )

    (:goal
        (and (clear a) (clear j) (clear e) (clear g) (clear l) (ontable m) (ontable b) (ontable e) (ontable f) (ontable k) (on i c) (on l k) (on c d) (on d f) (on a m) (on g i) (on j b) (holding h))
    )

    
    
    
)

