
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-13-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m - object
    )

    (:init
        (clear i)
        (clear g)
        (clear a)
        (clear c)
        (ontable i)
        (ontable g)
        (ontable f)
        (ontable k)
        (on b k)
        (on h e)
        (on e l)
        (on m h)
        (on j b)
        (on d f)
        (on a m)
        (on l j)
        (on c d)
        (handempty )
    )

    (:goal
        (and (clear d) (clear a) (clear i) (clear g) (ontable i) (ontable g) (ontable f) (ontable k) (on b k) (on h e) (on e l) (on m h) (on d f) (on a m) (on l j) (on j b) (holding c))
    )

    
    
    
)

