
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear m)
        (clear a)
        (clear j)
        (clear f)
        (clear g)
        (ontable h)
        (ontable j)
        (ontable e)
        (ontable f)
        (ontable n)
        (on k c)
        (on m k)
        (on i n)
        (on d i)
        (on c l)
        (on l b)
        (on b e)
        (on a h)
        (on g d)
        (handempty )
    )

    (:goal
        (and (clear a) (clear j) (clear f) (clear g) (clear k) (ontable h) (ontable j) (ontable e) (ontable f) (ontable n) (on k c) (on d i) (on c l) (on g d) (on l b) (on b e) (on a h) (on i n) (holding m))
    )

    
    
    
)

