
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear m)
        (clear b)
        (clear c)
        (clear j)
        (clear l)
        (ontable h)
        (ontable j)
        (ontable e)
        (ontable f)
        (ontable n)
        (on l f)
        (on i n)
        (on k g)
        (on d i)
        (on m a)
        (on b e)
        (on c k)
        (on a h)
        (on g d)
        (handempty )
    )

    (:goal
        (and (clear m) (clear c) (clear j) (clear e) (clear l) (ontable h) (ontable j) (ontable e) (ontable f) (ontable n) (on k g) (on m a) (on d i) (on g d) (on c k) (on l f) (on i n) (on a h) (holding b))
    )

    
    
    
)

