
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear e)
        (clear f)
        (clear c)
        (ontable l)
        (ontable n)
        (ontable h)
        (on f b)
        (on d m)
        (on e l)
        (on b j)
        (on k g)
        (on m a)
        (on g d)
        (on c k)
        (on a h)
        (on i n)
        (on j i)
        (handempty )
    )

    (:goal
        (and (clear e) (clear b) (clear c) (ontable l) (ontable n) (ontable h) (on d m) (on e l) (on b j) (on i n) (on k g) (on m a) (on c k) (on a h) (on g d) (on j i) (holding f))
    )

    
    
    
)

