
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-11-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k - object
    )

    (:init
        (clear b)
        (clear h)
        (clear j)
        (clear e)
        (clear g)
        (ontable b)
        (ontable c)
        (ontable j)
        (ontable i)
        (ontable g)
        (on k a)
        (on f i)
        (on d c)
        (on e d)
        (on h k)
        (on a f)
        (handempty )
    )

    (:goal
        (and (clear d) (clear b) (clear h) (clear j) (clear g) (ontable b) (ontable c) (ontable j) (ontable i) (ontable g) (on k a) (on f i) (on d c) (on h k) (on a f) (holding e))
    )

    
    
    
)

