
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-11-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k - object
    )

    (:init
        (clear j)
        (clear e)
        (clear b)
        (clear h)
        (ontable i)
        (ontable d)
        (ontable b)
        (ontable c)
        (on k a)
        (on e g)
        (on f i)
        (on g c)
        (on j d)
        (on h k)
        (on a f)
        (handempty )
    )

    (:goal
        (and (clear b) (clear j) (clear e) (clear k) (ontable i) (ontable d) (ontable b) (ontable c) (on k a) (on e g) (on f i) (on g c) (on j d) (on a f) (holding h))
    )

    
    
    
)

