
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear j)
        (clear f)
        (clear h)
        (ontable l)
        (ontable f)
        (ontable c)
        (on i c)
        (on a g)
        (on k e)
        (on j l)
        (on b d)
        (on d i)
        (on g k)
        (on e b)
        (on h a)
        (handempty )
    )

    (:goal
        (and (clear j) (clear f) (clear a) (ontable l) (ontable f) (ontable c) (on i c) (on a g) (on k e) (on j l) (on b d) (on d i) (on g k) (on e b) (holding h))
    )

    
    
    
)

