
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear g)
        (clear f)
        (clear a)
        (clear h)
        (ontable l)
        (ontable f)
        (ontable a)
        (ontable c)
        (on i c)
        (on h j)
        (on k e)
        (on j l)
        (on b d)
        (on d i)
        (on g k)
        (on e b)
        (handempty )
    )

    (:goal
        (and (clear a) (clear h) (clear f) (clear k) (ontable l) (ontable f) (ontable a) (ontable c) (on i c) (on k e) (on h j) (on j l) (on b d) (on d i) (on e b) (holding g))
    )

    
    
    
)

