
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-13-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m - object
    )

    (:init
        (clear i)
        (clear b)
        (clear f)
        (ontable g)
        (ontable m)
        (ontable k)
        (on c j)
        (on f d)
        (on d c)
        (on i g)
        (on l k)
        (on b m)
        (on j a)
        (on e h)
        (on a e)
        (on h l)
        (handempty )
    )

    (:goal
        (and (clear i) (clear d) (clear b) (ontable g) (ontable m) (ontable k) (on c j) (on i g) (on d c) (on l k) (on b m) (on j a) (on e h) (on a e) (on h l) (holding f))
    )

    
    
    
)

