
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem strips-gripper-x-10)
    (:domain gripper-strips)

    (:objects
        ball1 ball10 ball11 ball12 ball13 ball14 ball15 ball16 ball17 ball18 ball19 ball2 ball20 ball21 ball22 ball3 ball4 ball5 ball6 ball7 ball8 ball9 left right rooma roomb - object
    )

    (:init
        (room rooma)
        (room roomb)
        (ball ball9)
        (ball ball22)
        (ball ball17)
        (ball ball3)
        (ball ball14)
        (ball ball7)
        (ball ball15)
        (ball ball5)
        (ball ball13)
        (ball ball12)
        (ball ball11)
        (ball ball10)
        (ball ball8)
        (ball ball6)
        (ball ball19)
        (ball ball2)
        (ball ball4)
        (ball ball18)
        (ball ball20)
        (ball ball16)
        (ball ball21)
        (ball ball1)
        (at-robby roomb)
        (at ball11 roomb)
        (at ball17 roomb)
        (at ball4 rooma)
        (at ball15 roomb)
        (at ball13 roomb)
        (at ball18 roomb)
        (at ball10 roomb)
        (at ball8 rooma)
        (at ball5 rooma)
        (at ball14 roomb)
        (at ball6 rooma)
        (at ball20 roomb)
        (at ball19 roomb)
        (at ball1 roomb)
        (at ball2 roomb)
        (at ball7 rooma)
        (at ball21 roomb)
        (at ball9 rooma)
        (at ball12 roomb)
        (at ball16 roomb)
        (gripper left)
        (gripper right)
        (carry ball22 left)
        (carry ball3 right)
    )

    (:goal
        (and (room rooma) (room roomb) (ball ball9) (ball ball22) (ball ball17) (ball ball3) (ball ball14) (ball ball7) (ball ball15) (ball ball5) (ball ball13) (ball ball12) (ball ball11) (ball ball10) (ball ball8) (ball ball6) (ball ball19) (ball ball2) (ball ball4) (ball ball18) (ball ball20) (ball ball16) (ball ball21) (ball ball1) (at-robby roomb) (free left) (at ball11 roomb) (at ball17 roomb) (at ball4 rooma) (at ball15 roomb) (at ball13 roomb) (at ball18 roomb) (at ball10 roomb) (at ball8 rooma) (at ball5 rooma) (at ball14 roomb) (at ball6 rooma) (at ball20 roomb) (at ball19 roomb) (at ball1 roomb) (at ball2 roomb) (at ball7 rooma) (at ball21 roomb) (at ball9 rooma) (at ball22 roomb) (at ball12 roomb) (at ball16 roomb) (gripper left) (gripper right) (carry ball3 right))
    )

    
    
    
)

