
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear d)
        (clear e)
        (clear b)
        (ontable a)
        (ontable d)
        (ontable c)
        (on e a)
        (on b c)
        (handempty )
    )

    (:goal
        (and (clear d) (clear e) (clear c) (ontable a) (ontable d) (ontable c) (on e a) (holding b))
    )

    
    
    
)

