
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear e)
        (clear f)
        (ontable b)
        (ontable c)
        (on f d)
        (on d a)
        (on a c)
        (on e b)
        (handempty )
    )

    (:goal
        (and (clear b) (clear f) (ontable b) (ontable c) (on d a) (on a c) (on f d) (holding e))
    )

    
    
    
)

