
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear a)
        (clear d)
        (clear f)
        (ontable e)
        (ontable b)
        (ontable f)
        (on c b)
        (on d e)
        (on a c)
        (handempty )
    )

    (:goal
        (and (clear d) (clear f) (clear c) (ontable e) (ontable b) (ontable f) (on c b) (on d e) (holding a))
    )

    
    
    
)

