
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear a)
        (clear d)
        (clear f)
        (ontable d)
        (ontable b)
        (ontable c)
        (on f e)
        (on a c)
        (on e b)
        (handempty )
    )

    (:goal
        (and (clear a) (clear d) (clear e) (ontable d) (ontable b) (ontable c) (on a c) (on e b) (holding f))
    )

    
    
    
)

