
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-7-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g - object
    )

    (:init
        (clear a)
        (clear g)
        (ontable d)
        (ontable e)
        (on f c)
        (on g b)
        (on b e)
        (on a f)
        (on c d)
        (handempty )
    )

    (:goal
        (and (clear a) (clear b) (ontable d) (ontable e) (on f c) (on b e) (on a f) (on c d) (holding g))
    )

    
    
    
)

