
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear a)
        (clear b)
        (clear g)
        (clear d)
        (clear h)
        (ontable a)
        (ontable b)
        (ontable c)
        (ontable e)
        (ontable f)
        (on g e)
        (on h f)
        (on d c)
        (handempty )
    )

    (:goal
        (and (clear a) (clear b) (clear g) (clear d) (clear f) (ontable a) (ontable b) (ontable c) (ontable e) (ontable f) (on g e) (on d c) (holding h))
    )

    
    
    
)

