
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear e)
        (clear b)
        (clear c)
        (ontable a)
        (ontable e)
        (ontable c)
        (on b a)
        (holding d)
    )

    (:goal
        (and (clear d) (clear e) (clear b) (clear c) (ontable a) (ontable d) (ontable e) (ontable c) (on b a) (handempty ))
    )

    
    
    
)

