
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear a)
        (clear d)
        (clear e)
        (ontable a)
        (ontable e)
        (ontable b)
        (on c b)
        (on d c)
        (holding f)
    )

    (:goal
        (and (clear a) (clear d) (clear e) (clear f) (ontable a) (ontable e) (ontable b) (ontable f) (on c b) (on d c) (handempty ))
    )

    
    
    
)

