
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-4-0)
    (:domain BLOCKS)

    (:objects
        a b c d - object
    )

    (:init
        (clear c)
        (ontable d)
        (holding b)
        (on a d)
        (on c a)
    )

    (:goal
        (and (clear b) (clear c) (ontable d) (ontable b) (handempty ) (on a d) (on c a))
    )

    
    
    
)

