
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-7-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g - object
    )

    (:init
        (clear a)
        (clear e)
        (ontable d)
        (ontable g)
        (on e g)
        (on f c)
        (on a f)
        (on c d)
        (holding b)
    )

    (:goal
        (and (clear a) (clear e) (clear b) (ontable d) (ontable g) (ontable b) (on a f) (on e g) (on f c) (on c d) (handempty ))
    )

    
    
    
)

