
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-7-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g - object
    )

    (:init
        (clear e)
        (clear b)
        (ontable d)
        (ontable e)
        (on b a)
        (on f c)
        (on a f)
        (on c d)
        (holding g)
    )

    (:goal
        (and (clear g) (clear e) (clear b) (ontable d) (ontable g) (ontable e) (on b a) (on a f) (on f c) (on c d) (handempty ))
    )

    
    
    
)

