
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear e)
        (clear f)
        (ontable b)
        (ontable f)
        (on a g)
        (on e h)
        (on h c)
        (on c a)
        (on g b)
        (holding d)
    )

    (:goal
        (and (clear d) (clear e) (clear f) (ontable d) (ontable b) (ontable f) (on a g) (on e h) (on h c) (on c a) (on g b) (handempty ))
    )

    
    
    
)

