
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem briefcase-o5)
    (:domain briefcase)

    (:objects
        l0 l1 l2 l3 l4 l5 - location
        o0 o1 o2 o3 o4 - portable
    )

    (:init
        (at o3 l4)
        (at o4 l0)
        (at o0 l4)
        (at o2 l4)
        (at o1 l4)
        (is-at l4)
        (in o0)
        (in o1)
        (in o2)
    )

    (:goal
        (and (at o3 l4) (at o4 l0) (at o0 l4) (at o2 l4) (at o1 l4) (is-at l4) (in o3) (in o0) (in o1) (in o2))
    )

    
    
    
)

