
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear e)
        (clear b)
        (clear a)
        (ontable e)
        (ontable a)
        (ontable c)
        (on d c)
        (on b d)
        (handempty )
    )

    (:goal
        (and (clear b) (clear a) (ontable a) (ontable c) (on d c) (on b d) (holding e))
    )

    
    
    
)

