
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear b)
        (clear a)
        (clear c)
        (clear e)
        (clear f)
        (ontable d)
        (ontable b)
        (ontable a)
        (ontable c)
        (ontable e)
        (on f d)
        (handempty )
    )

    (:goal
        (and (clear b) (clear a) (clear c) (clear f) (ontable d) (ontable b) (ontable a) (ontable c) (on f d) (holding e))
    )

    
    
    
)

