
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-7-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g - object
    )

    (:init
        (clear d)
        (clear b)
        (clear a)
        (ontable e)
        (ontable g)
        (ontable d)
        (on b c)
        (on a g)
        (on f e)
        (on c f)
        (handempty )
    )

    (:goal
        (and (clear b) (clear a) (ontable g) (ontable e) (on a g) (on b c) (on f e) (on c f) (holding d))
    )

    
    
    
)

