
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear d)
        (clear c)
        (clear h)
        (clear e)
        (ontable e)
        (ontable b)
        (ontable f)
        (ontable h)
        (on c a)
        (on a g)
        (on g b)
        (on d f)
        (handempty )
    )

    (:goal
        (and (clear e) (clear d) (clear c) (ontable e) (ontable b) (ontable f) (on c a) (on d f) (on g b) (on a g) (holding h))
    )

    
    
    
)

