
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem mixed-f10-p5-u0-v0-g0-a0-n0-A0-B0-N0-F0-r0)
    (:domain miconic)

    (:objects
        f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 - floor
        p0 p1 p2 p3 p4 - passenger
    )

    (:init
        (above f3 f9)
        (above f1 f3)
        (above f7 f8)
        (above f2 f9)
        (above f1 f4)
        (above f1 f7)
        (above f1 f8)
        (above f0 f6)
        (above f5 f8)
        (above f1 f5)
        (above f2 f3)
        (above f3 f4)
        (above f3 f7)
        (above f3 f8)
        (above f4 f7)
        (above f4 f8)
        (above f1 f2)
        (above f2 f4)
        (above f0 f9)
        (above f4 f5)
        (above f3 f5)
        (above f2 f7)
        (above f2 f8)
        (above f5 f6)
        (above f6 f9)
        (above f2 f5)
        (above f0 f3)
        (above f5 f9)
        (above f0 f4)
        (above f1 f6)
        (above f0 f7)
        (above f0 f8)
        (above f7 f9)
        (above f0 f5)
        (above f4 f6)
        (above f3 f6)
        (above f6 f7)
        (above f1 f9)
        (above f6 f8)
        (above f8 f9)
        (above f0 f1)
        (above f0 f2)
        (above f5 f7)
        (above f4 f9)
        (above f2 f6)
        (origin p3 f6)
        (origin p2 f3)
        (origin p4 f9)
        (origin p1 f7)
        (origin p0 f3)
        (destin p3 f2)
        (destin p1 f5)
        (destin p0 f6)
        (destin p2 f5)
        (destin p4 f1)
        (lift-at f9)
        (boarded p4)
    )

    (:goal
        (and (above f3 f9) (above f1 f3) (above f7 f8) (above f2 f9) (above f1 f4) (above f1 f7) (above f1 f8) (above f0 f6) (above f1 f5) (above f2 f3) (above f3 f4) (above f3 f7) (above f3 f8) (above f4 f7) (above f4 f8) (above f4 f9) (above f1 f2) (above f2 f4) (above f0 f9) (above f4 f5) (above f3 f5) (above f2 f7) (above f2 f8) (above f5 f6) (above f6 f9) (above f2 f5) (above f0 f3) (above f5 f9) (above f0 f4) (above f1 f6) (above f0 f7) (above f0 f8) (above f7 f9) (above f0 f5) (above f4 f6) (above f3 f6) (above f6 f7) (above f1 f9) (above f6 f8) (above f8 f9) (above f0 f1) (above f0 f2) (above f5 f7) (above f5 f8) (above f2 f6) (origin p3 f6) (origin p2 f3) (origin p4 f9) (origin p1 f7) (origin p0 f3) (destin p3 f2) (destin p1 f5) (destin p0 f6) (destin p2 f5) (destin p4 f1) (lift-at f1) (boarded p4))
    )

    
    
    
)

