
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear d)
        (clear c)
        (ontable e)
        (ontable a)
        (on c a)
        (on d b)
        (on b e)
        (handempty )
    )

    (:goal
        (and (clear b) (clear c) (ontable e) (ontable a) (on c a) (on b e) (holding d))
    )

    
    
    
)

