
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-4-0)
    (:domain BLOCKS)

    (:objects
        a b c d - object
    )

    (:init
        (clear b)
        (clear a)
        (ontable d)
        (ontable c)
        (handempty )
        (on b c)
        (on a d)
    )

    (:goal
        (and (clear a) (clear c) (ontable d) (ontable c) (holding b) (on a d))
    )

    
    
    
)

