
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear e)
        (clear a)
        (clear c)
        (ontable d)
        (ontable b)
        (ontable a)
        (on f d)
        (on e b)
        (on c f)
        (handempty )
    )

    (:goal
        (and (clear e) (clear f) (clear a) (ontable d) (ontable b) (ontable a) (on f d) (on e b) (holding c))
    )

    
    
    
)

