
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear e)
        (clear b)
        (clear c)
        (ontable d)
        (ontable f)
        (ontable a)
        (on e a)
        (on b d)
        (on c f)
        (handempty )
    )

    (:goal
        (and (clear b) (clear a) (clear c) (ontable d) (ontable f) (ontable a) (on b d) (on c f) (holding e))
    )

    
    
    
)

