
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-7-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g - object
    )

    (:init
        (clear f)
        (clear a)
        (clear c)
        (ontable e)
        (ontable d)
        (ontable f)
        (on g e)
        (on c d)
        (on a b)
        (on b g)
        (handempty )
    )

    (:goal
        (and (clear b) (clear f) (clear c) (ontable d) (ontable e) (ontable f) (on g e) (on c d) (on b g) (holding a))
    )

    
    
    
)

