
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-4-0)
    (:domain BLOCKS)

    (:objects
        a b c d - object
    )

    (:init
        (clear d)
        (clear b)
        (ontable a)
        (ontable c)
        (handempty )
        (on b c)
        (on d a)
    )

    (:goal
        (and (clear d) (clear c) (ontable a) (ontable c) (holding b) (on d a))
    )

    
    
    
)

