
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-4-0)
    (:domain BLOCKS)

    (:objects
        a b c d - object
    )

    (:init
        (clear d)
        (clear b)
        (clear c)
        (ontable b)
        (ontable a)
        (ontable c)
        (handempty )
        (on d a)
    )

    (:goal
        (and (clear b) (clear a) (clear c) (ontable b) (ontable a) (ontable c) (holding d))
    )

    
    
    
)

