
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-13-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m - object
    )

    (:init
        (clear m)
        (clear b)
        (clear a)
        (clear g)
        (ontable m)
        (ontable b)
        (ontable f)
        (ontable k)
        (on i c)
        (on l k)
        (on d f)
        (on a e)
        (on g i)
        (on e h)
        (on c d)
        (on h l)
        (holding j)
    )

    (:goal
        (and (clear m) (clear a) (clear j) (clear g) (ontable m) (ontable b) (ontable f) (ontable k) (on i c) (on l k) (on c d) (on j b) (on d f) (on h l) (on g i) (on e h) (on a e) (handempty ))
    )

    
    
    
)

