
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-13-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m - object
    )

    (:init
        (clear a)
        (clear j)
        (clear g)
        (clear l)
        (clear k)
        (ontable j)
        (ontable e)
        (ontable f)
        (ontable l)
        (ontable k)
        (on i c)
        (on h e)
        (on m h)
        (on d f)
        (on a m)
        (on g i)
        (on c d)
        (holding b)
    )

    (:goal
        (and (clear b) (clear a) (clear j) (clear g) (clear l) (ontable j) (ontable e) (ontable f) (ontable l) (ontable k) (on i c) (on b k) (on h e) (on m h) (on d f) (on a m) (on g i) (on c d) (handempty ))
    )

    
    
    
)

