
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-13-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m - object
    )

    (:init
        (clear g)
        (clear d)
        (clear a)
        (ontable c)
        (ontable d)
        (ontable k)
        (on i c)
        (on b k)
        (on h e)
        (on e l)
        (on m h)
        (on a m)
        (on g i)
        (on l j)
        (on j b)
        (holding f)
    )

    (:goal
        (and (clear g) (clear d) (clear f) (ontable d) (ontable k) (ontable c) (on i c) (on b k) (on f a) (on h e) (on e l) (on m h) (on a m) (on g i) (on l j) (on j b) (handempty ))
    )

    
    
    
)

