
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear m)
        (clear a)
        (clear j)
        (clear f)
        (clear g)
        (ontable j)
        (ontable e)
        (ontable f)
        (ontable g)
        (ontable n)
        (on k c)
        (on m k)
        (on d i)
        (on c l)
        (on a d)
        (on l b)
        (on b e)
        (on i n)
        (holding h)
    )

    (:goal
        (and (clear m) (clear h) (clear j) (clear f) (clear g) (ontable j) (ontable e) (ontable f) (ontable g) (ontable n) (on k c) (on m k) (on d i) (on c l) (on a d) (on l b) (on b e) (on i n) (on h a) (handempty ))
    )

    
    
    
)

