
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-14-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l m n - object
    )

    (:init
        (clear g)
        (clear m)
        (clear f)
        (clear h)
        (ontable j)
        (ontable e)
        (ontable n)
        (ontable c)
        (on d i)
        (on m j)
        (on a d)
        (on l b)
        (on b e)
        (on g c)
        (on i n)
        (on f l)
        (on h a)
        (holding k)
    )

    (:goal
        (and (clear m) (clear h) (clear f) (clear k) (ontable j) (ontable e) (ontable n) (ontable c) (on k g) (on d i) (on m j) (on a d) (on b e) (on l b) (on g c) (on i n) (on f l) (on h a) (handempty ))
    )

    
    
    
)

