
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-11-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k - object
    )

    (:init
        (clear i)
        (clear b)
        (clear a)
        (ontable c)
        (ontable d)
        (ontable h)
        (on i f)
        (on e g)
        (on b h)
        (on f e)
        (on g c)
        (on a j)
        (on j d)
        (holding k)
    )

    (:goal
        (and (clear b) (clear k) (clear a) (ontable d) (ontable h) (ontable c) (on i f) (on e g) (on k i) (on b h) (on f e) (on g c) (on a j) (on j d) (handempty ))
    )

    
    
    
)

