
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear h)
        (clear j)
        (clear g)
        (clear l)
        (ontable j)
        (ontable c)
        (ontable f)
        (ontable h)
        (on i c)
        (on k e)
        (on b d)
        (on d i)
        (on g k)
        (on e b)
        (on l f)
        (holding a)
    )

    (:goal
        (and (clear a) (clear j) (clear g) (clear l) (ontable j) (ontable h) (ontable f) (ontable c) (on i c) (on k e) (on b d) (on d i) (on g k) (on e b) (on l f) (on a h) (handempty ))
    )

    
    
    
)

