
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear b)
        (clear a)
        (clear i)
        (clear f)
        (clear g)
        (ontable a)
        (ontable c)
        (ontable f)
        (ontable g)
        (ontable k)
        (on i c)
        (on j e)
        (on d j)
        (on e k)
        (on l d)
        (on b l)
        (holding h)
    )

    (:goal
        (and (clear b) (clear a) (clear h) (clear i) (clear f) (ontable a) (ontable c) (ontable f) (ontable g) (ontable k) (on i c) (on j e) (on d j) (on e k) (on h g) (on l d) (on b l) (handempty ))
    )

    
    
    
)

