
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-12-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h i j k l - object
    )

    (:init
        (clear j)
        (clear i)
        (clear f)
        (clear l)
        (ontable d)
        (ontable b)
        (ontable e)
        (ontable g)
        (on i c)
        (on j e)
        (on f a)
        (on h g)
        (on l d)
        (on a h)
        (on c b)
        (holding k)
    )

    (:goal
        (and (clear j) (clear i) (clear l) (clear k) (ontable e) (ontable g) (ontable d) (ontable b) (on i c) (on j e) (on f a) (on k f) (on h g) (on l d) (on a h) (on c b) (handempty ))
    )

    
    
    
)

