
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-4-0)
    (:domain BLOCKS)

    (:objects
        a b c d - object
    )

    (:init
        (clear c)
        (ontable a)
        (holding d)
        (on b a)
        (on c b)
    )

    (:goal
        (and (clear d) (ontable a) (handempty ) (on b a) (on d c) (on c b))
    )

    
    
    
)

