
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear d)
        (clear a)
        (clear c)
        (clear e)
        (ontable d)
        (ontable e)
        (ontable a)
        (ontable c)
        (holding b)
    )

    (:goal
        (and (clear d) (clear b) (clear a) (clear c) (ontable e) (ontable d) (ontable a) (ontable c) (on b e) (handempty ))
    )

    
    
    
)

