
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear e)
        (ontable c)
        (on b d)
        (on d c)
        (on e b)
        (holding a)
    )

    (:goal
        (and (clear a) (ontable c) (on e b) (on a e) (on d c) (on b d) (handempty ))
    )

    
    
    
)

