
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear e)
        (clear f)
        (clear c)
        (ontable d)
        (ontable a)
        (ontable c)
        (on e a)
        (on f d)
        (holding b)
    )

    (:goal
        (and (clear e) (clear b) (clear f) (ontable d) (ontable a) (ontable c) (on e a) (on b c) (on f d) (handempty ))
    )

    
    
    
)

