
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear b)
        (clear f)
        (clear a)
        (ontable d)
        (ontable b)
        (ontable c)
        (on a c)
        (on f d)
        (holding e)
    )

    (:goal
        (and (clear e) (clear b) (clear a) (ontable d) (ontable b) (ontable c) (on a c) (on f d) (on e f) (handempty ))
    )

    
    
    
)

