
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-7-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g - object
    )

    (:init
        (clear b)
        (clear a)
        (clear c)
        (ontable d)
        (ontable e)
        (ontable a)
        (on g e)
        (on c d)
        (on b g)
        (holding f)
    )

    (:goal
        (and (clear b) (clear f) (clear c) (ontable e) (ontable d) (ontable a) (on f a) (on g e) (on c d) (on b g) (handempty ))
    )

    
    
    
)

