
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-7-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g - object
    )

    (:init
        (clear b)
        (clear e)
        (clear f)
        (clear g)
        (ontable d)
        (ontable g)
        (ontable e)
        (ontable b)
        (on f c)
        (on c d)
        (holding a)
    )

    (:goal
        (and (clear b) (clear a) (clear e) (clear f) (ontable e) (ontable g) (ontable d) (ontable b) (on f c) (on a g) (on c d) (handempty ))
    )

    
    
    
)

