
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear d)
        (clear f)
        (clear c)
        (ontable e)
        (ontable h)
        (ontable c)
        (on f a)
        (on g e)
        (on a g)
        (on d h)
        (holding b)
    )

    (:goal
        (and (clear d) (clear b) (clear f) (ontable c) (ontable e) (ontable h) (on g e) (on a g) (on f a) (on b c) (on d h) (handempty ))
    )

    
    
    
)

