
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear d)
        (clear f)
        (ontable e)
        (ontable c)
        (on g e)
        (on a g)
        (on f a)
        (on d b)
        (on b c)
        (holding h)
    )

    (:goal
        (and (clear d) (clear h) (ontable e) (ontable c) (on g e) (on a g) (on h f) (on f a) (on d b) (on b c) (handempty ))
    )

    
    
    
)

