(define (problem visitall_3)
  (:domain visitall)
  (:objects r1 r2 r3 r4 - row c1 c2 c3 c4 - column)
  (:init (at_row r1)(at_column c1)(visited r1 c1)
    (adjacent_rows r1 r2)    
(adjacent_rows r2 r3)    
(adjacent_rows r3 r4)
    (adjacent_columns c1 c2)    
(adjacent_columns c2 c3)    
(adjacent_columns c3 c4))
  (:goal (and 
    (visited r1 c1)
    (visited r1 c2)
    (visited r1 c3)
    (visited r1 c4)
    (visited r2 c1)
    (visited r2 c2)
    (visited r2 c3)
    (visited r2 c4)
    (visited r3 c1)
    (visited r3 c2)
    (visited r3 c3)
    (visited r3 c4)
    (visited r4 c1)
    (visited r4 c2)
    (visited r4 c3)
    (visited r4 c4))))
