
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-4-0)
    (:domain BLOCKS)

    (:objects
        a b c d - object
    )

    (:init
        (clear d)
        (clear b)
        (clear c)
        (ontable a)
        (ontable d)
        (ontable c)
        (handempty )
        (on b a)
    )

    (:goal
        (and (clear d) (clear b) (ontable a) (ontable d) (holding c) (on b a))
    )

    
    
    
)

