
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear d)
        (clear c)
        (ontable a)
        (ontable d)
        (on b a)
        (on e b)
        (on c e)
        (handempty )
    )

    (:goal
        (and (clear c) (ontable a) (on b a) (on e b) (on c e) (holding d))
    )

    
    
    
)

