
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-8-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f g h - object
    )

    (:init
        (clear c)
        (clear g)
        (clear h)
        (clear e)
        (clear f)
        (ontable a)
        (ontable b)
        (ontable c)
        (ontable e)
        (ontable f)
        (on g b)
        (on h d)
        (on d a)
        (handempty )
    )

    (:goal
        (and (clear c) (clear g) (clear h) (clear f) (ontable a) (ontable b) (ontable c) (ontable f) (on g b) (on h d) (on d a) (holding e))
    )

    
    
    
)

