
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem briefcase-o12)
    (:domain briefcase)

    (:objects
        l0 l1 l10 l11 l12 l2 l3 l4 l5 l6 l7 l8 l9 - location
        o0 o1 o10 o11 o2 o3 o4 o5 o6 o7 o8 o9 - portable
    )

    (:init
        (at o9 l10)
        (at o1 l0)
        (at o7 l10)
        (at o11 l10)
        (at o8 l10)
        (at o4 l10)
        (at o2 l10)
        (at o5 l10)
        (at o6 l10)
        (at o10 l10)
        (at o3 l10)
        (at o0 l8)
        (is-at l10)
        (in o2)
        (in o9)
        (in o6)
        (in o10)
        (in o11)
        (in o7)
        (in o3)
        (in o5)
        (in o4)
        (in o8)
    )

    (:goal
        (and (at o9 l10) (at o1 l0) (at o8 l10) (at o4 l10) (at o7 l10) (at o2 l10) (at o5 l10) (at o11 l10) (at o6 l10) (at o10 l10) (at o3 l10) (at o0 l8) (is-at l10) (in o2) (in o9) (in o6) (in o10) (in o7) (in o3) (in o5) (in o4) (in o8))
    )

    
    
    
)

