
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear b)
        (clear c)
        (ontable d)
        (ontable a)
        (on b a)
        (on c d)
        (holding e)
    )

    (:goal
        (and (clear e) (clear b) (clear c) (ontable e) (ontable d) (ontable a) (on b a) (on c d) (handempty ))
    )

    
    
    
)

