
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear a)
        (clear c)
        (ontable e)
        (ontable c)
        (on a b)
        (on b e)
        (holding d)
    )

    (:goal
        (and (clear d) (clear a) (clear c) (ontable d) (ontable e) (ontable c) (on a b) (on b e) (handempty ))
    )

    
    
    
)

