
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-5-0)
    (:domain BLOCKS)

    (:objects
        a b c d e - object
    )

    (:init
        (clear b)
        (clear c)
        (ontable e)
        (ontable a)
        (on c a)
        (on b e)
        (holding d)
    )

    (:goal
        (and (clear d) (clear b) (clear c) (ontable d) (ontable e) (ontable a) (on c a) (on b e) (handempty ))
    )

    
    
    
)

