
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear d)
        (clear f)
        (clear c)
        (ontable d)
        (ontable b)
        (ontable c)
        (on f e)
        (on e b)
        (holding a)
    )

    (:goal
        (and (clear d) (clear f) (clear a) (clear c) (ontable d) (ontable b) (ontable a) (ontable c) (on f e) (on e b) (handempty ))
    )

    
    
    
)

