
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem BLOCKS-6-0)
    (:domain BLOCKS)

    (:objects
        a b c d e f - object
    )

    (:init
        (clear d)
        (clear e)
        (clear b)
        (ontable d)
        (ontable a)
        (ontable c)
        (on e a)
        (on b c)
        (holding f)
    )

    (:goal
        (and (clear e) (clear d) (clear b) (clear f) (ontable d) (ontable f) (ontable a) (ontable c) (on e a) (on b c) (handempty ))
    )

    
    
    
)

